# Generated by Django 5.2.1 on 2025-10-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogbookmark",
            options={
                "verbose_name": "Blog Bookmark",
                "verbose_name_plural": "Blog Bookmarks",
            },
        ),
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="bloglike",
            options={"verbose_name": "Blog Like", "verbose_name_plural": "Blog Likes"},
        ),
        migrations.AlterModelOptions(
            name="historicalblogbookmark",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Blog Bookmark",
                "verbose_name_plural": "historical Blog Bookmarks",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalblogcategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Blog Category",
                "verbose_name_plural": "historical Blog Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbloglike",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Blog Like",
                "verbose_name_plural": "historical Blog Likes",
            },
        ),
    ]
