# Generated by Django 5.2.1 on 2025-05-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_coreposition_wing_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="wing",
            name="short_title",
            field=models.CharField(default="ACM", max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
