# Generated by Django 5.2.1 on 2025-05-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="position",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="wing",
        ),
        migrations.DeleteModel(
            name="CorePosition",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Wing",
        ),
    ]
