# Generated by Django 5.2.1 on 2025-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_profile_position_remove_profile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sub",
            field=models.CharField(
                blank=True, help_text="Google sub ID", max_length=50, null=True
            ),
        ),
    ]
