# Generated by Django 5.2.1 on 2025-05-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_google_login",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
