# Generated by Django 5.2.1 on 2025-10-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalnoticecategory",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="noticecategory",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="noticetag",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="historicalnoticecategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="historicalnoticecategory",
            name="description",
        ),
        migrations.RemoveField(
            model_name="historicalnoticecategory",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="historicalnoticecategory",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="noticecategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="noticecategory",
            name="description",
        ),
        migrations.RemoveField(
            model_name="noticecategory",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="noticecategory",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="noticetag",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="noticetag",
            name="description",
        ),
        migrations.RemoveField(
            model_name="noticetag",
            name="updated_at",
        ),
    ]
