# Generated by Django 5.2.1 on 2025-10-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0002_rename_name_historicalnoticecategory_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalnoticecategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Notice Category",
                "verbose_name_plural": "historical Notice Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="noticecategory",
            options={
                "verbose_name": "Notice Category",
                "verbose_name_plural": "Notice Categories",
            },
        ),
        migrations.AlterField(
            model_name="historicalnoticecategory",
            name="title",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="noticecategory",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="noticetag",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
