# Generated by Django 5.2.1 on 2025-05-31 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Member",
        ),
        migrations.AlterModelOptions(
            name="coreposition",
            options={
                "ordering": ["position_order"],
                "verbose_name": "Core Committee Position",
                "verbose_name_plural": "Core Committee Positions",
            },
        ),
        migrations.AlterModelOptions(
            name="wing",
            options={"ordering": ["position_order"]},
        ),
        migrations.AddField(
            model_name="coreposition",
            name="position_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wing",
            name="position_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
