# Generated by Django 5.2.1 on 2025-10-15 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0002_committee_panel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committee",
            options={
                "ordering": ["-year"],
                "verbose_name": "Committee",
                "verbose_name_plural": "Committees",
            },
        ),
        migrations.AlterField(
            model_name="panel",
            name="committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panels",
                to="committees.committee",
            ),
        ),
        migrations.AlterField(
            model_name="panel",
            name="type",
            field=models.CharField(
                choices=[("ADVISOR", "Advisor"), ("STUDENT", "Student")], max_length=20
            ),
        ),
    ]
