name: Migration Builder
on:
  push:
    branches: [dev, main]

permissions:
  contents: write

jobs:
  create-migrations:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - uses: actions/checkout@v4

    - name: Load environment variables from sample.env
      run: |
        cp sample.env .env
        set -a
        source .env
        set +a

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements/base.txt

    - name: Create migrations
      env:
        SERVER_TYPE: dbmigrate
      run: 
        python manage.py makemigrations
  
    - name: Commit migrations
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Generate migrations" || echo "No changes to commit"
        git push
