from .logout import LogoutView
from .otp_verify import OTPVerifyView
from .password_change import PasswordChangeView
from .password_reset import PasswordResetView
from .password_reset_mail import PasswordResetMailView
from .signin import SigninView
from .signin_google import SigninGoogleView
from .signup import SignupView
from .signup_google import SignupGoogleView
from .token_verify import TokenVerifyView
from .user_info import UserInfoView
